# Generated by Django 5.2 on 2025-05-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500, unique=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
